# Generated by Django 5.2.4 on 2025-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_watchprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchprogress',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='duration',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='watchprogress',
            name='updated_at',
        ),
    ]
