# Generated by Django 5.2.4 on 2025-07-31 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_watchprogress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('user', 'movie_id')},
        ),
    ]
