# Generated by Django 5.2.4 on 2025-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_watchprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprogress',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
